name: Main workflow
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        emacs_version:
          - '25.1'
          - '25.2'
          - '25.3'
          - '26.1'
          - '26.2'
          - '26.3'
          - '27.1'
          - '27.2'
          - '28.1'
          - 'snapshot'

        include:
          - os: ubuntu-latest
            emacs_version: 'snapshot'
            allow_failure: true
          - os: macos-latest
            emacs_version: 'snapshot'
            allow_failure: true
          - os: windows-latest
            emacs_version: 'snapshot'
            allow_failure: true
    steps:
    - uses: actions/checkout@v2
    
    - uses: jcs090218/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - uses: emacs-eask/setup-eask@master
      with:
        version: 'snapshot'

    - name: Run tests
      if: matrix.allow_failure != true
      run: 'make test'

    - name: Run tests (allow failure)
      if: matrix.allow_failure == true
      run: 'make test || true'
